тип Failed to start server
Error: listen EADDRINUSE: address already in use 127.0.0.1:3000
    at <unknown> (Error: listen EADDRINUSE: address already in use 127.0.0.1:3000) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '127.0.0.1',
  port: 3000
}spring:
  application:
    name: merchandise-service
  config:
    import: optional:configserver:http://localhost:8761

  profiles:
    active: shared-database

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5434}/${POSTGRES_DB:nebula_db}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 20000

  jpa:
    properties:
      hibernate:
        default_schema: merchandise_service
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false


server:
  port: ${SERVER_PORT:8084}

logging:
  level:
    org.springframework: INFO
    com.netflix.discovery: WARN
    com.netflix.eureka: WARN
    c.n.d.s.t.d.RetryableEurekaHttpClient: ERROR
    
    org.hibernate: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type: WARN

    org.apache.catalina: WARN
    org.apache.tomcat: WARN
    com.zaxxer.hikari: WARN

    org.springframework.cloud: WARN
    io.netty: WARN

    pse.nebula: INFO

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    enabled: true
    registry-fetch-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 5
    instance-info-replication-interval-seconds: 30
    eureka-service-url-poll-interval-seconds: 10
  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
